# Generated by Django 4.0.5 on 2022-06-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.CharField(max_length=9, verbose_name='Telegram ID пользователя')),
                ('telegram_user_first_name', models.CharField(max_length=15, verbose_name='Имя пользователя')),
                ('telegram_user_last_name', models.CharField(max_length=15, verbose_name='Фамилия пользователя')),
                ('telegram_user_nickname', models.CharField(max_length=30, verbose_name='Никнейм пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
