# Generated by Django 4.0.5 on 2022-06-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teletroyka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_user_first_name',
            field=models.CharField(blank=True, max_length=15, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_user_last_name',
            field=models.CharField(blank=True, max_length=15, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_user_nickname',
            field=models.CharField(blank=True, max_length=30, verbose_name='Никнейм пользователя'),
        ),
    ]
