# Generated by Django 4.0.5 on 2022-06-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teletroyka', '0002_alter_telegramuser_telegram_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_user_first_name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_user_last_name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_user_nickname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Никнейм пользователя'),
        ),
    ]
