# Generated by Django 4.0.5 on 2022-06-03 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teletroyka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_value', models.CharField(max_length=16, verbose_name='Номер карты')),
                ('expired_month', models.CharField(max_length=2, verbose_name='Месяц истечения')),
                ('expired_year', models.CharField(max_length=2, verbose_name='Год истечения')),
                ('card_holder', models.CharField(max_length=30, verbose_name='Владелец карты')),
                ('telegramuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teletroyka.telegramuser')),
            ],
            options={
                'verbose_name': 'Банковская карта',
                'verbose_name_plural': 'Банковские карты',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_datetime', models.DateTimeField(auto_now=True, verbose_name='Дата и время транзакции')),
                ('tr_status', models.CharField(max_length=10, verbose_name='Статус транзакции')),
                ('tr_obj_description', models.CharField(max_length=500, verbose_name='Описание покупки')),
                ('bankcard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chetverka.bankcard')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(max_length=15, verbose_name='Название билета')),
                ('ticket_number', models.CharField(max_length=10, unique=True, verbose_name='Номер билета')),
                ('ticket_datetime', models.DateTimeField(verbose_name='Дата и время отправления')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chetverka.transaction')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.CreateModel(
            name='PricesAndProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=6, verbose_name='Цена')),
                ('product', models.CharField(max_length=50, verbose_name='Товар')),
                ('service', models.CharField(max_length=100, verbose_name='Описание товара')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chetverka.ticket')),
            ],
            options={
                'verbose_name': 'Цена и продукт',
                'verbose_name_plural': 'Цены и продукты',
            },
        ),
    ]
