# Generated by Django 4.0.4 on 2022-06-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chetverka', '0002_logger'),
    ]

    operations = [
        migrations.AddField(
            model_name='logger',
            name='error',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ошибка'),
        ),
    ]
